# Standard ruby style guide, linter, and formatter https://github.com/testdouble/standard
# to check the style of files run:-
# $ bundle exec standardrb
ignore:
  - 'flexitime.gemspec'

# Standard will default to telling RuboCop to target the currently running version of Ruby
# instead set this to minimum version of Ruby supported by Flexitime
# which prevents an offence being flagged for the Style/SlicingWithRange cop that is releveant to Ruby 2.6+
ruby_version: 2.5
